### ISSUE TITLE
Readme.MD

### ISSUE THREAD

**Issue by z1mEk** [thomas-villagers/domoticz-yamaha#10]
You need to change Readme.MD, because it contains a url to @stas-demydiuk repo.
@thomas-villagers , @stas-demydiuk  Let's set the rules of development so as not to make a mess.
Is Thomas' repository is official for Domoticz users?

**Comment by pipiche38** [comment]
Since the latest version of the plugin, when adding the Yamaha hardware in Domoticz it is expected to enter 2 additional fields "Inputs Name" and "DSP Program Name". It would be good to clarify what is expected here
