### ISSUE TITLE
Are these functions needed?

### ISSUE THREAD

**Issue by z1mEk** [thomas-villagers/domoticz-yamaha#14]
https://github.com/thomas-villagers/domoticz-yamaha/blob/577dc210d22878534e7bee6e919993bf4a6a7f0e/plugin.py#L422

**Comment by thomas-villagers** [comment]
as I can see it: no, not anymore

**Comment by z1mEk** [comment]
Remove?

**Comment by thomas-villagers** [comment]
yes!
