### ISSUE TITLE
'onMessage' failed 'TypeError':'onMessage() takes 2 positional arguments but 4 were given'.

### ISSUE THREAD

**Issue by pipiche38** [thomas-villagers/domoticz-yamaha#15]
I have move now from Synology to a Raspberry Pi , running Domoticz V3.8153 (c)2012-2017 GizMoCuz

In addition of not having the new icons, I'm getting those error message.

Apr 23 07:58:47 pi3.localdomain domoticz[3986]: 2018-04-23 07:58:47.311  Error: (Yamaha) 'onMessage' failed 'TypeError':'onMessage() takes 2 positional arguments but 4 were given'.
Apr 23 07:58:47 pi3.localdomain domoticz[3986]: 2018-04-23 07:58:47.311  Error: (Yamaha) 'onMessage' failed 'TypeError':'onMessage() takes 2 positional arguments but 4 were given'.
Apr 23 07:58:56 pi3.localdomain domoticz[3986]: 2018-04-23 07:58:56.727  Error: (Yamaha) 'onMessage' failed 'TypeError':'onMessage() takes 2 positional arguments but 4 were given'.

**Comment by z1mEk** [comment]
I have same problem in Raspberry - I must added 2 parameters (status, extra) to onMessage function. What it depends on?

**Comment by z1mEk** [comment]
Can used optional arguments... *status, *extra ?

**Comment by thomas-villagers** [comment]
Hi! The Domoticz Guys constantly changed the Python API which causes some confusion ... I guess all of us are using the beta Version of Domiticz. Maybe you should also switch from stable to beta -- but PLEASE make a backup!

- thomas

**Comment by z1mEk** [comment]
We officially assume that domoticz-yamaha is for the Beta version? Maybe let's write it in README?

**Comment by zaraki673** [comment]
When we wrote it you don't read it ....

let's see on my plugin, i wrote :
Domoticz version 3.87xx or greater.

but you ask for the same error ....

;)

2018-04-23 13:48 GMT+02:00 Gabriel <notifications@github.com>:

**Comment by z1mEk** [comment]
I understand it but I am wondering how to help users who want to use the stable version.

**Comment by thomas-villagers** [comment]
I added a note in the readme to make clear that Domoticz beta is needed. It should not be too hard to modify onCommand etc. to accept the "appropriate" parameters for the stable branch. Maybe someone can figure this out?

- thomas

**Comment by pipiche38** [comment]
Will be going to beta. Currently recompiling it ;-)

**Comment by pipiche38** [comment]
I do confirm that moving to Beta solved the issue.
