### ISSUE TITLE
Error when activating the Yamaha plugin (with domoticz Beta )

### ISSUE THREAD

**Issue by pipiche38** [thomas-villagers/domoticz-yamaha#18]
I'm now running Beta V3.9317 on a Rpi3

And I don't see any devices !

Apr 25 16:44:58 pi3 domoticz[17779]: 2018-04-25 16:44:58.503  (Yamaha) Started.
Apr 25 16:44:58 pi3 domoticz[17779]: 2018-04-25 16:44:58.796  (Yamaha) Entering work loop.
Apr 25 16:44:58 pi3 domoticz[17779]: 2018-04-25 16:44:58.796  (Yamaha) Initialized version 2.0.0, author 'thomasvillagers'
Apr 25 16:44:58 pi3 domoticz[17779]: 2018-04-25 16:44:58.808  Error: (Yamaha) 'onStart' failed 'KeyError'.
Apr 25 16:44:58 pi3 domoticz[17779]: 2018-04-25 16:44:58.809  Error: (Yamaha) ----> Line 368 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onStart
Apr 25 16:44:58 pi3 domoticz[17779]: 2018-04-25 16:44:58.809  Error: (Yamaha) ----> Line 277 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onStart
Apr 25 16:45:08 pi3 domoticz[17779]: 2018-04-25 16:45:08.332  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Apr 25 16:45:08 pi3 domoticz[17779]: 2018-04-25 16:45:08.332  Error: (Yamaha) ----> Line 396 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 25 16:45:08 pi3 domoticz[17779]: 2018-04-25 16:45:08.332  Error: (Yamaha) ----> Line 350 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat

**Comment by z1mEk** [comment]
Hi, remove the Yamaha icon from Custom Icons - it should help.

**Comment by z1mEk** [comment]
I will add a delete command before adding the icon so that no one has such a problem anymore.

**Comment by pipiche38** [comment]
Don't know if this has been commited, but I still have errors and no devices 

Apr 30 19:56:12 pi3 domoticz[568]: 2018-04-30 19:56:12.153  (Yamaha) Started.
Apr 30 19:56:12 pi3 domoticz[568]: 2018-04-30 19:56:12.499  (Yamaha) Entering work loop.
Apr 30 19:56:12 pi3 domoticz[568]: 2018-04-30 19:56:12.500  (Yamaha) Initialized version 2.0.0, author 'thomasvillagers'
Apr 30 19:56:12 pi3 domoticz[568]: 2018-04-30 19:56:12.517  Error: (Yamaha) 'onStart' failed 'KeyError'.
Apr 30 19:56:12 pi3 domoticz[568]: 2018-04-30 19:56:12.518  Error: (Yamaha) ----> Line 368 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onStart
Apr 30 19:56:12 pi3 domoticz[568]: 2018-04-30 19:56:12.518  Error: (Yamaha) ----> Line 277 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onStart
Apr 30 19:56:22 pi3 domoticz[568]: 2018-04-30 19:56:22.048  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Apr 30 19:56:22 pi3 domoticz[568]: 2018-04-30 19:56:22.048  Error: (Yamaha) ----> Line 396 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:22 pi3 domoticz[568]: 2018-04-30 19:56:22.048  Error: (Yamaha) ----> Line 350 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:32 pi3 domoticz[568]: 2018-04-30 19:56:32.032  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Apr 30 19:56:32 pi3 domoticz[568]: 2018-04-30 19:56:32.032  Error: (Yamaha) ----> Line 396 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:32 pi3 domoticz[568]: 2018-04-30 19:56:32.032  Error: (Yamaha) ----> Line 350 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:42 pi3 domoticz[568]: 2018-04-30 19:56:42.015  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Apr 30 19:56:42 pi3 domoticz[568]: 2018-04-30 19:56:42.015  Error: (Yamaha) ----> Line 396 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:42 pi3 domoticz[568]: 2018-04-30 19:56:42.015  Error: (Yamaha) ----> Line 350 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:52 pi3 domoticz[568]: 2018-04-30 19:56:52.050  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Apr 30 19:56:52 pi3 domoticz[568]: 2018-04-30 19:56:52.050  Error: (Yamaha) ----> Line 396 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:56:52 pi3 domoticz[568]: 2018-04-30 19:56:52.050  Error: (Yamaha) ----> Line 350 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:57:02 pi3 domoticz[568]: 2018-04-30 19:57:02.037  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Apr 30 19:57:02 pi3 domoticz[568]: 2018-04-30 19:57:02.037  Error: (Yamaha) ----> Line 396 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
Apr 30 19:57:02 pi3 domoticz[568]: 2018-04-30 19:57:02.037  Error: (Yamaha) ----> Line 350 in /var/lib/domoticz/plugins/domoticz-yamaha/plugin.py, function onHeartbeat
[support@pi3 ~]$

**Comment by z1mEk** [comment]
You removed the Yamaha icon manually?

**Comment by pipiche38** [comment]
No, should I ?

Here is the full plugin directory

ll -l -R domoticz-yamaha/
domoticz-yamaha/:
total 80
-rw-r--r-- 1 domoticz domoticz 35141 Apr 25 17:07 LICENSE
-rw-r--r-- 1 domoticz domoticz  3346 Apr 25 17:07 README.md
drwxr-xr-x 2 domoticz domoticz  4096 Apr 26 19:32 __pycache__
-rw-r--r-- 1 domoticz domoticz  9046 Apr 25 17:07 icons.zip
drwxr-xr-x 2 domoticz domoticz  4096 Apr 25 17:07 images
-rw-r--r-- 1 domoticz domoticz 17119 Apr 26 11:28 plugin.py

domoticz-yamaha/__pycache__:
total 16
-rw-r--r-- 1 domoticz domoticz 13944 Apr 26 19:32 plugin.cpython-36.pyc

domoticz-yamaha/images:
total 364
-rw-r--r-- 1 domoticz domoticz 147137 Apr 25 17:07 devices.png
-rw-r--r-- 1 domoticz domoticz 223307 Apr 25 17:07 remote.png

**Comment by pipiche38** [comment]
[support@pi3 domoticz-yamaha]$ git rev-parse HEAD
a51c3873b02d2c05d729fc566d0674d71be3137c

**Comment by z1mEk** [comment]
Restart domoticz, should fix this problem. When loading the plugin, the icon is created again.

**Comment by pipiche38** [comment]
Looks not. I did restart, no error in the logs, but no new icon loaded 

Anyway it is not a big issue.

What you have done is already awesome

**Comment by pipiche38** [comment]
Fix with PR #37
