### ISSUE TITLE
Still issue with latest verson !

### ISSUE THREAD

**Issue by pipiche38** [thomas-villagers/domoticz-yamaha#23]
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.151  Status: (Yamaha) Initialized version 2.0.0, author 'thomasvillagers'
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.160  Error: (Yamaha) 'onStart' failed 'KeyError'.
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.160  Error: (Yamaha) ----> Line 403 in '/var/lib/domoticz/plugins/domoticz-yamaha-old/plugin.py', function onStart
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.160  Error: (Yamaha) ----> Line 304 in '/var/lib/domoticz/plugins/domoticz-yamaha-old/plugin.py', function onStart
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.261  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.261  Error: (Yamaha) ----> Line 431 in '/var/lib/domoticz/plugins/domoticz-yamaha-old/plugin.py', function onHeartbeat
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.261  Error: (Yamaha) ----> Line 385 in '/var/lib/domoticz/plugins/domoticz-yamaha-old/plugin.py', function onHeartbeat
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.261  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.262  Error: (Yamaha) ----> Line 431 in '/var/lib/domoticz/plugins/domoticz-yamaha-old/plugin.py', function onHeartbeat
Sep 13 16:56:18 pi3 domoticz[8180]: 2018-09-13 16:56:18.262  Error: (Yamaha) ----> Line 385 in '/var/lib/domoticz/plugins/domoticz-yamaha-old/plugin.py', function onHeartbeat

**Comment by pipiche38** [comment]
Could you kindly explain what zone field should contains ?

**Comment by pipiche38** [comment]
Sep 13 16:59:59 pi3 domoticz[8512]: 2018-09-13 16:59:59.755  (Yamaha) Calling message handler 'onHeartbeat'.
Sep 13 16:59:59 pi3 domoticz[8512]: 2018-09-13 16:59:59.755  (Yamaha) onHeartbeat called. Connected: True
Sep 13 16:59:59 pi3 domoticz[8512]: 2018-09-13 16:59:59.756  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Sep 13 16:59:59 pi3 domoticz[8512]: 2018-09-13 16:59:59.756  Error: (Yamaha) ----> Line 431 in '/var/lib/domoticz/plugins/domoticz-yamaha/plugin.py', function onHeartbeat
Sep 13 16:59:59 pi3 domoticz[8512]: 2018-09-13 16:59:59.756  Error: (Yamaha) ----> Line 385 in '/var/lib/domoticz/plugins/domoticz-yamaha/plugin.py', function onHeartbeat
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.759  (Yamaha) Pushing 'onHeartbeatCallback' on to queue
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.783  (Yamaha) Processing 'onHeartbeatCallback' message
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.783  (Yamaha) Calling message handler 'onHeartbeat'.
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.783  (Yamaha) onHeartbeat called. Connected: True
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.783  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.784  Error: (Yamaha) ----> Line 431 in '/var/lib/domoticz/plugins/domoticz-yamaha/plugin.py', function onHeartbeat
Sep 13 17:00:09 pi3 domoticz[8512]: 2018-09-13 17:00:09.784  Error: (Yamaha) ----> Line 385 in '/var/lib/domoticz/plugins/domoticz-yamaha/plugin.py', function onHeartbeat
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.304  (Yamaha) Pushing 'onHeartbeatCallback' on to queue
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.306  (Yamaha) Processing 'onHeartbeatCallback' message
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.306  (Yamaha) Calling message handler 'onHeartbeat'.
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.306  (Yamaha) onHeartbeat called. Connected: True
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.306  Error: (Yamaha) 'onHeartbeat' failed 'AttributeError':''BasePlugin' object has no attribute 'zones''.
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.306  Error: (Yamaha) ----> Line 431 in '/var/lib/domoticz/plugins/domoticz-yamaha/plugin.py', function onHeartbeat
Sep 13 17:00:24 pi3 domoticz[8512]: 2018-09-13 17:00:24.306  Error: (Yamaha) ----> Line 385 in '/var/lib/domoticz/plugins/domoticz-yamaha/plugin.py', function onHeartbeat

**Comment by thomas-villagers** [comment]
yes I can confirm. Error vanishes when I delete and recreate device, but gets me more errors ...

**Comment by z1mEk** [comment]
My last Pull Request solves the Icon problem. However, there is a second major problem, the function Create() does not create a device. That's why in the get...Device functions an invalid key error occurs. I dont know why it does not create these devices :(

**Comment by pipiche38** [comment]
PR #37 fixing the issue
