### ISSUE TITLE
Audio1 input 

### ISSUE THREAD

**Issue by satanasinc** [thomas-villagers/domoticz-yamaha#5]
Hi! 

The plugin works great, thanks great job.
How can I see in Domoticz the Audio1 inputdomoticz displays HDMI1.

Thank you in advance and greetings from Spain

**Comment by thomas-villagers** [comment]
Hey! I'm sorry, Audio Inputs are not implemented yet. I might add them if I find the time. 

- thomas

**Comment by z1mEk** [comment]
After the last merge it's probably out of date?
