### ISSUE TITLE
Would be great to integrate rx-v581

### ISSUE THREAD

**Issue by pipiche38** [thomas-villagers/domoticz-yamaha#6]
I have installed your plugin and it works pretty great.

However it would be good to add a number of Input lines as well as DSP.
https://fr.yamaha.com/fr/products/audio_visual/av_receivers_amps/rx-v581/index.html

Here attached is a short extract of the domoticz log. Would be happy to contribute , but my knowledge on python are quiet low.

[pp.txt](https://github.com/thomas-villagers/domoticz-yamaha/files/1877071/pp.txt)

**Comment by thomas-villagers** [comment]
Adding DSP is a good idea, I'll look into it. What does " a number of input lines" mean?

**Comment by pipiche38** [comment]
Sorry for the confusion, I was just suggesting to add DSP

**Comment by stas-demydiuk** [comment]
@pipiche38 DSP control and additional inputs are added in #7

**Comment by pipiche38** [comment]
Integrated in the Plugin enhacement #7
